spring:
  application:
    name: "Spring Security Demo"

  datasource:
    url: jdbc:mysql://localhost:3306/Spring_Security_Demo
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    devtools:
      restart:
        enabled: true
        exclude: com/shubh/module5/Spring_Security_Demp/dto

  security:
    # Create a single user's login and pass, for multiple users, configuration is defined
    # in a java class
    # roles ADMIN, USER, MANAGER
    user:
      name: shubh
      password: shubh
      roles: ADMIN, USER, MANAGER

jwt:
  # should be atleast 256 bits long to be secure, otherwise exception is thrown
  secretKey: HOLA_AMIGOa-string-secret-at-least-256-bits-long