spring:
  application:
    name: Prod_Ready_Features

  datasource:
    url: jdbc:mysql://localhost:3306/Prod_Ready_Features
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create # flag changed to update to see updated by / enver auditing behavior by changing auditor aware modifier value

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    devtools:
      restart:
        enabled: true
        exclude: com/shubh/module4/Prod_Ready_Features/dto

    server:
      # change the port of the server to see rest client behavior, we need the other service running which also takes port 8080
      # two applications running on same port are not allowed
      port: 9000

    # custom property defined using @Value annotation, injected using application.yaml
    employeeService:
      base:
        url: http://localhost:8080/