server:
  # change the port of the server to see rest client behavior, we need the other service running which also takes port 8080
  # two applications running on same port are not allowed
  port: 9000

  # custom property defined using @Value annotation, injected using application.yaml
employeeService:
  base:
    url: http://localhost:8080/
spring:
  application:
    name: Prod_Ready_Features

  datasource:
    url: jdbc:mysql://localhost:3306/Prod_Ready_Features
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create # flag changed to update to see updated by / enver auditing behavior by changing auditor aware modifier value

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    devtools:
      restart:
        enabled: true
        exclude: com/shubh/module4/Prod_Ready_Features/dto

logging:
  # not required, spring automatically looks for this file_name on the classpath, if a custom_file_name is used for config_file
  # then it needs to be specified here
  #config: classpath:logback-spring.xml
  # every setting below will be overriden if logback-spring file is present
  level:
#    root: debug
    # set log level for a package, should correspond to compiled class file path[PATH FROM SOURCE_ROOT]
    # Specific package path overrides root baseline to capture absolute maximum TRACE details.
    com.shubh.module4.Prod_Ready_Features.clients: TRACE
    com.shubh.module4.Prod_Ready_Features.config: INFO

  pattern:
    # 1. Standard Fallback Pattern: Prints full timestamp, unshortened fully qualified class path (%c), and the message string.
    # console: "%d [%c] --- %m%n"

    # 2. Optimized Custom Pattern: Formats date safely (MM=Month, mm=Minute), injects log level severity,
    # and truncates the logger path to show only the final 2 segments (%c{2}) for maximum readability.
    console: "%d{dd-MM-yy HH:mm:ss} [%level] [%c{2}] --- %m%n"
    # 💾 Independent pattern configuration specifically for file logging.
    # Injects a green ANSI timestamp, severity level, truncated 2-depth logger path, execution thread, and the message string.
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%level] %c{2} [%t] %m%n"

  file:
    name: application.log # create a file if doesn't exist already to store logs