logging:
  file:
    name: logs/application.log
  level:
    root: info
    com.Module3.Practice.CollegeManagement.service: trace

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SS} | [%level] | [%c{2}] ---- %m%n"
    console: "%d{dd-MM-yy HH:mm:ss} [%level] [%c{2}] --- %m%n"

spring:
  application:
    name: CollegeManagement

  datasource:
    url: jdbc:mysql://localhost:3306/College
    username: root # change appropriately
    password: root

  jpa:
    defer-datasource-initialization: true # run sql scripts after hibernate initialises the schema
    show-sql: true # show sql queries

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format-sql: false # pretty print sql queries
