spring.application.name= SpringBootWebTutorial

# to check how the data is being persisted the database
# H2 console available at '/h2-console'. Database available at 'jdbc:h2:file:/Users/shubhgaur/Documents/SpringBoot/Module2/tutorialDB/db'
spring.h2.console.enabled= true

# use a file database instead of an in-memory db
# specify the type of dp and path to store it
spring.datasource.url= jdbc:h2:file:/Users/shubhgaur/Documents/SpringBoot/Module2/tutorialDB/db

# OPTIONAL: Define a username and password for db
# very important to use the same username & password after db creation
# otherwise server doesn't start because jdbc connection is not established due
# authentication issue
spring.datasource.username= shubhDB
spring.datasource.password= gaur

# one more step before we can use our database
# Exception thrown because table does not exist
#org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "EMPLOYEES_SEQ" not found; SQL statement:
#select next value for employees_seq [90036-232]

#spring.jpa.hibernate.ddl-auto = none - [default setting]!!,doesn't initialise the tables on server start
# creates a new table every time the server starts
#spring.jpa.hibernate.ddl-auto = create

# avoid creating a new table everytime the server boots and use the persisted one
# initialises the db if it is not present
spring.jpa.hibernate.ddl-auto = update